import { Ground } from '../types/ground.types';

export const DEFAULT_SAMPLE_GROUNDS: Ground[] = [
  {
    id: 'ground-sample-1',
    name: 'Gentlemen Turf & Box Arena',
    address: 'Plot 42, Near Vaishno Devi Circle, S.G. Highway, Ahmedabad',
    mapLocationUrl: 'https://maps.google.com/?q=23.1254,72.5321',
    description: 'Premium international-standard astro-turf box cricket ground with high-intensity LED floodlights, professional pitch bounce, and dugout seating.',
    images: ['https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?q=80&w=1000'],
    weekdayPrice: 1500,
    weekendPrice: 2500,
    morningPrice: 1500,
    morningWeekendPrice: 2500,
    eveningPrice: 1800,
    eveningWeekendPrice: 2800,
    timeSlots: ['7:00 AM - 10:30 AM', '2:30 PM - 5:50 PM'],
    hasParking: true,
    hasCharging: true,
    hasFirstAid: true,
    hasDugout: true,
    hasWashroom: true,
    hasChangingRoom: true,
    contactName: 'Ramesh Kumar',
    contactPhone: '+919876543210',
    rules: '1. Spike shoes strictly prohibited on astro-turf.\n2. Arrive 15 mins prior to slot.\n3. No smoking or alcohol.\n4. Teams bring tennis cricket balls.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ground-sample-2',
    name: 'Royal Strikers Box Cricket',
    address: 'Opposite Drive-In Cinema, Thaltej Road, Ahmedabad',
    mapLocationUrl: 'https://maps.google.com/?q=23.0485,72.5186',
    description: 'Spacious box cricket venue featuring shock-absorbing turf, electronic scoreboard, covered spectator dugout, and ample parking.',
    images: ['https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=1000'],
    weekdayPrice: 1800,
    weekendPrice: 2800,
    morningPrice: 1800,
    morningWeekendPrice: 2800,
    eveningPrice: 2200,
    eveningWeekendPrice: 3200,
    timeSlots: ['7:00 AM - 10:30 AM', '2:30 PM - 5:50 PM'],
    hasParking: true,
    hasCharging: true,
    hasFirstAid: true,
    hasDugout: true,
    hasWashroom: true,
    hasChangingRoom: true,
    contactName: 'Vikram Patel',
    contactPhone: '+919812345678',
    rules: '1. Flat sports shoes or turf shoes mandatory.\n2. Maintain discipline on field.\n3. Respect slot timings.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ground-sample-3',
    name: 'Champions Turf Arena',
    address: 'Near Rajpath Club, Bodakdev, Ahmedabad',
    mapLocationUrl: 'https://maps.google.com/?q=23.0360,72.5080',
    description: 'State-of-the-art enclosed box cricket stadium with double-layered safety net, night floodlights, and refreshment lounge.',
    images: ['https://images.unsplash.com/photo-1587280501635-68a0e82cd5ff?q=80&w=1000'],
    weekdayPrice: 2000,
    weekendPrice: 3000,
    morningPrice: 2000,
    morningWeekendPrice: 3000,
    eveningPrice: 2500,
    eveningWeekendPrice: 3500,
    timeSlots: ['7:00 AM - 10:30 AM', '2:30 PM - 5:50 PM'],
    hasParking: true,
    hasCharging: true,
    hasFirstAid: true,
    hasDugout: true,
    hasWashroom: true,
    hasChangingRoom: true,
    contactName: 'Amit Sharma',
    contactPhone: '+919988776655',
    rules: '1. Soft/heavy tennis balls permitted.\n2. Max 16 players per slot.\n3. Keep dugout clean.',
    createdAt: new Date().toISOString(),
  },
];
